# docker-compose.yml
services:
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"  # Use port 8001 to avoid conflict with your backend
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      # Add CORS for local development
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["http://localhost:3000","http://localhost:5000","http://localhost:8001"]
    restart: unless-stopped

volumes:
  chroma_data:
    driver: local